@Ticketing.command_HostAddress = http://localhost:5001

GET {{ Ticketing.command_HostAddress }}/weatherforecast/
Accept: application/json

###
Post {{ Ticketing.command_HostAddress }}/api/ticket/
Accept: application/json
content-type: application/json

{
  "username": "Luis Suare<",
  "typeError": "Error Desktop",
  "detailError": "No jala tu mamada"
}
