@Ticketing.command_HostAddress = http://localhost:5001

GET {{ Ticketing.command_HostAddress }}/weatherforecast/
Accept: application/json

###
Post {{ Ticketing.command_HostAddress }}/api/ticket/
Accept: application/json
content-type: application/json

{
  "username": "SuperPuta@gmail.com",
  "typeError": 3,
  "detailError": "Esta apagada tu putada"
}
