@Ticketing.command_HostAddress = http://localhost:5001

GET {{ Ticketing.command_HostAddress }}/weatherforecast/
Accept: application/json

###
Post {{ Ticketing.command_HostAddress }}/api/ticket/
Accept: application/json
content-type: application/json

{
  "username": "Soygay@gmail.com",
  "typeError": 3,
  "detailError": "Necesito pito"
}

### Update ticket

Put {{ Ticketing.command_HostAddress }}/api/tickets/019fc40e-58f3-743e-b38d-5bcf913b33f1
Accept: application/json
content-type: application/json

{
  "ticketType": 5,
  "description": "Eres un putote, ya vi como mamas",
  "username": "poradict@gmail.com"
}

### Delete ticket

DELETE {{ Ticketing.command_HostAddress }}/api/tickets/019fc3a9-1a40-78eb-a352-2ec7eecced55?username=admin@gmail.com
Accept: application/json

### Get tickets
