// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tiketing.Query.Infrastructure.Persistence;

#nullable disable

namespace Tiketing.Query.Infrastructure.Persintence.Mogrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tiketing.Query.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastModificateOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modificate_on");

                    b.Property<string>("LastModifieBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modifie_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_employess");

                    b.ToTable("employess", (string)null);
                });

            modelBuilder.Entity("Tiketing.Query.Domain.TicketTypes.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_type");

                    b.ToTable("ticket_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FatalError"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WarningError"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NotFoundDeviceError"
                        },
                        new
                        {
                            Id = 4,
                            Name = "InternalDeviceError"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ManagePersonError"
                        });
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModificateOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modificate_on");

                    b.Property<string>("LastModifieBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modifie_by");

                    b.Property<int?>("TicketType")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type");

                    b.HasKey("Id")
                        .HasName("pk_tickects");

                    b.ToTable("tickects", (string)null);
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Tickets.TicketEmployee", b =>
                {
                    b.Property<Guid>("TickedId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticked_id");

                    b.Property<Guid>("EmployedId")
                        .HasColumnType("uuid")
                        .HasColumnName("employed_id");

                    b.HasKey("TickedId", "EmployedId")
                        .HasName("pk_ticket_employess");

                    b.HasIndex("EmployedId")
                        .HasDatabaseName("ix_ticket_employess_employed_id");

                    b.ToTable("ticket_employess", (string)null);
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("Tiketing.Query.Domain.Addresses.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employess");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId")
                                .HasConstraintName("fk_employess_employess_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Tickets.TicketEmployee", b =>
                {
                    b.HasOne("Tiketing.Query.Domain.Employees.Employee", "Employee")
                        .WithMany("TicketEmployees")
                        .HasForeignKey("EmployedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_employess_employess_employed_id");

                    b.HasOne("Tiketing.Query.Domain.Tickets.Ticket", "Ticket")
                        .WithMany("TicketEmployees")
                        .HasForeignKey("TickedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_employess_tickects_ticked_id");

                    b.Navigation("Employee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Employees.Employee", b =>
                {
                    b.Navigation("TicketEmployees");
                });

            modelBuilder.Entity("Tiketing.Query.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("TicketEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
